version: "3"
services:
  server:
    build: ./services/server
    ports:
      - "8080:8080"
    container_name: gsmk-poll-api
  client:
    build: ./services/client
    ports:
      - "80:80"
    container_name: gsmk-poll-client