services:
  client:
    build: ./client/
    ports:
      - "8080:80"
    container_name: gsmk-poll-client
    depends_on:
      - server
  server:
    build: ./server/
    ports:
      - "7000:7000"
    container_name: gsmk-poll-server