export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const CALL_ROUTE = '/call'
export const CALL_SUCCESS_ROUTE = '/call/success'
export const CALL_ROUTE_DETAIL = '/call_form'
export const POLL_ROUTE = '/poll'
export const USERS_ROUTE = '/users'
export const Templates_ROUTE = '/Templates'
export const HOME_ROUTE = '/'

